name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t ecsproject:latest .
        docker tag ecsproject:latest 156041431760.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecsproject:latest

    - name: Install Trivy
      run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

    - name: Run Trivy Scan
      run: ./trivy image --severity CRITICAL 156041431760.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecsproject:latest

    - name: Save Trivy Report
      run: ./trivy image --format table --output trivy-report.txt 156041431760.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ecsproject:latest

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.txt

    - name: Push Docke
