name: Terraform Apply

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Checkov
      run: pip install checkov

    - name: Run Checkov Scan
      working-directory: ./terraform
      run: checkov -d . --quiet --compact --output cli --framework terraform --soft-fail=false
      continue-on-error: false  # Fail on issues

    - name: Save Checkov Results
      working-directory: ./terraform
      run: checkov -d . --quiet --compact --output junitxml > checkov-report.xml
      continue-on-error: true  # Save results regardless of failures

    - name: Upload Checkov Report
      uses: actions/upload-artifact@v3
      with:
        name: checkov-report
        path: ./terraform/checkov-report.xml

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve
